kumuluzee:
  datasources:
    - jndi-name: jdbc/CustomersDS
      connection-url: jdbc:h2:mem:customers
      username: sa
      password: 
      pool:
        max-size: 2
  persistence-units:
    - name: "kumuluzee-samples-jpa"
      continue-on-error: false
