load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_pkg",
    sha256 = "8f9ee2dc10c1ae514ee599a8b42ed99fa262b757058f65ad3c384289ff70c4b8",
    urls = [
        "https://github.com/bazelbuild/rules_pkg/releases/download/0.9.1/rules_pkg-0.9.1.tar.gz",
    ],
)

RULES_JVM_EXTERNAL_TAG = "5.3"
RULES_JVM_EXTERNAL_SHA ="d31e369b854322ca5098ea12c69d7175ded971435e55c18dd9dd5f29cc5249ac"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/releases/download/%s/rules_jvm_external-%s.tar.gz" % (RULES_JVM_EXTERNAL_TAG, RULES_JVM_EXTERNAL_TAG)
)

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()

load("@rules_jvm_external//:defs.bzl", "maven_install")

# when the list of dependencies changes
# bazel run @unpinned_maven//:pin
maven_install(
    artifacts = [
        "antlr:antlr:2.7.7",
        "com.fasterxml:classmate:1.5.1",
        "com.fasterxml.jackson.core:jackson-annotations:2.12.2",
        "com.fasterxml.jackson.core:jackson-core:2.12.2",
        "com.fasterxml.jackson.core:jackson-databind:2.12.2",
        "com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:2.12.2",
        "com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.12.2",
        "com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.12.2",
        "com.h2database:h2:2.1.214",
        "com.kumuluz.ee:kumuluzee-cdi-weld:4.1.0",
        "com.kumuluz.ee:kumuluzee-common:4.1.0",
        "com.kumuluz.ee:kumuluzee-core:4.1.0",
        "com.kumuluz.ee:kumuluzee-jax-rs-jersey:4.1.0",
        "com.kumuluz.ee:kumuluzee-jpa-common:4.1.0",
        "com.kumuluz.ee:kumuluzee-jpa-hibernate:4.1.0",
        "com.kumuluz.ee:kumuluzee-jta-common:4.1.0",
        "com.kumuluz.ee:kumuluzee-jta-narayana:4.1.0",
        "com.kumuluz.ee:kumuluzee-servlet-jetty:4.1.0",
        "com.sun.istack:istack-commons-runtime:3.0.7",
        "com.sun.xml.fastinfoset:FastInfoset:1.2.15",
        "com.zaxxer:HikariCP:3.4.5",
        "io.agroal:agroal-api:1.9",
        "io.agroal:agroal-hikari:1.9",
        "io.agroal:agroal-narayana:1.9",
        "io.agroal:agroal-pool:1.9",
        "jakarta.activation:jakarta.activation-api:1.2.1",
        "jakarta.annotation:jakarta.annotation-api:1.3.5",
        "jakarta.el:jakarta.el-api:3.0.3",
        "jakarta.enterprise:jakarta.enterprise.cdi-api:2.0.2",
        "jakarta.inject:jakarta.inject-api:1.0.3",
        "jakarta.interceptor:jakarta.interceptor-api:1.2.5",
        "jakarta.resource:jakarta.resource-api:1.7.4",
        "jakarta.servlet:jakarta.servlet-api:4.0.4",
        "jakarta.transaction:jakarta.transaction-api:1.3.3",
        "jakarta.validation:jakarta.validation-api:2.0.2",
        "jakarta.ws.rs:jakarta.ws.rs-api:2.1.6",
        "jakarta.xml.bind:jakarta.xml.bind-api:2.3.2",
        "javax.activation:activation:1.1.1",
        "javax.activation:javax.activation-api:1.2.0",
        "javax.persistence:javax.persistence-api:2.2",
        "javax.xml.bind:jaxb-api:2.3.1",
        "net.bytebuddy:byte-buddy:1.11.12",
        "org.eclipse.jetty.http2:http2-client:10.0.9",
        "org.eclipse.jetty.http2:http2-common:10.0.9",
        "org.eclipse.jetty.http2:http2-hpack:10.0.9",
        "org.eclipse.jetty.http2:http2-http-client-transport:10.0.9",
        "org.eclipse.jetty.http2:http2-server:10.0.9",
        "org.eclipse.jetty:jetty-alpn-client:10.0.9",
        "org.eclipse.jetty:jetty-alpn-java-client:10.0.9",
        "org.eclipse.jetty:jetty-alpn-java-server:10.0.9",
        "org.eclipse.jetty:jetty-alpn-server:10.0.9",
        "org.eclipse.jetty:jetty-annotations:10.0.9",
        "org.eclipse.jetty:jetty-client:10.0.9",
        "org.eclipse.jetty:jetty-http:10.0.9",
        "org.eclipse.jetty:jetty-io:10.0.9",
        "org.eclipse.jetty:jetty-jndi:10.0.9",
        "org.eclipse.jetty:jetty-plus:10.0.9",
        "org.eclipse.jetty:jetty-security:10.0.9",
        "org.eclipse.jetty:jetty-server:10.0.9",
        "org.eclipse.jetty:jetty-servlet:10.0.9",
        "org.eclipse.jetty:jetty-util:10.0.9",
        "org.eclipse.jetty:jetty-webapp:10.0.9",
        "org.eclipse.jetty:jetty-xml:10.0.9",
        "org.eclipse.jetty.toolchain:jetty-servlet-api:4.0.6",
        "org.glassfish.hk2.external:aopalliance-repackaged:2.6.1",
        "org.glassfish.hk2.external:jakarta.inject:2.6.1",
        "org.glassfish.hk2:hk2-api:2.6.1",
        "org.glassfish.hk2:hk2-locator:2.6.1",
        "org.glassfish.hk2:hk2-utils:2.6.1",
        "org.glassfish.hk2:osgi-resource-locator:1.0.3",
        "org.glassfish.jaxb:jaxb-runtime:2.3.1",
        "org.glassfish.jaxb:txw2:2.3.1",
        "org.glassfish.jersey.connectors:jersey-jetty-connector:2.34",
        "org.glassfish.jersey.containers:jersey-container-servlet:2.34",
        "org.glassfish.jersey.containers:jersey-container-servlet-core:2.34",
        "org.glassfish.jersey.core:jersey-client:2.34",
        "org.glassfish.jersey.core:jersey-common:2.34",
        "org.glassfish.jersey.core:jersey-server:2.34",
        "org.glassfish.jersey.ext.cdi:jersey-cdi1x:2.34",
        "org.glassfish.jersey.ext.cdi:jersey-cdi1x-ban-custom-hk2-binding:2.34",
        "org.glassfish.jersey.ext.cdi:jersey-cdi1x-servlet:2.34",
        "org.glassfish.jersey.ext:jersey-entity-filtering:2.34",
        "org.glassfish.jersey.inject:jersey-hk2:2.34",
        "org.glassfish.jersey.media:jersey-media-json-jackson:2.34",
        "org.glassfish.jersey.media:jersey-media-sse:2.34",
        "org.hibernate.common:hibernate-commons-annotations:5.1.2.Final",
        "org.hibernate:hibernate-core:5.5.7.Final",
        "org.javassist:javassist:3.27.0-GA",
        "org.jboss.classfilewriter:jboss-classfilewriter:1.2.5.Final",
        "org.jboss:jandex:2.4.2.Final",
        "org.jboss:jboss-transaction-spi:7.6.0.Final",
        "org.jboss.logging:jboss-logging:3.4.2.Final",
        "org.jboss.narayana.jta:narayana-jta:5.10.6.Final",
        "org.jboss.weld.environment:weld-environment-common:3.1.8.Final",
        "org.jboss.weld.module:weld-jsf:3.1.8.Final",
        "org.jboss.weld.module:weld-jta:3.1.8.Final",
        "org.jboss.weld.module:weld-web:3.1.8.Final",
        "org.jboss.weld.probe:weld-probe-core:3.1.8.Final",
        "org.jboss.weld.servlet:weld-servlet-core:3.1.8.Final",
        "org.jboss.weld:weld-api:3.1.SP4",
        "org.jboss.weld:weld-core-impl:3.1.8.Final",
        "org.jboss.weld:weld-spi:3.1.SP4",
        "org.jvnet.staxex:stax-ex:1.8",
        "org.ow2.asm:asm:9.2",
        "org.ow2.asm:asm-analysis:9.2",
        "org.ow2.asm:asm-commons:9.2",
        "org.ow2.asm:asm-tree:9.2",
        "org.slf4j:slf4j-api:2.0.0-alpha6",
        "org.slf4j:slf4j-jdk14:2.0.0-alpha6",
        "org.yaml:snakeyaml:1.27",
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ]
)
