name: Sample Go Action

on:
  push:
    branches: [ develop ]
    paths:
      - 'monorepo/projects/algorithms/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./monorepo
    steps:
      # Replace the action with a similar one
      - uses: josejuanmontiel/on-call-tutti-action@v1.0.1
        with:
          lease-duration: 2h
          role: 'user'


