name: CI

on:
  workflow_dispatch:  
  push:
    branches: [ develop ]
    paths:
      - 'monorepo/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./monorepo
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Build bazel monorepo
        working-directory: ./monorepo
        run: bazelisk build //...
      # - name: Test bazel monorepo
      #   run: bazel test //...
