name: CI

on:
  push:
    branches: [ develop ]
  # pull_request:
  #   branches: [ develop ]

jobs:
  ci:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./monorepo
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Build bazel monorepo
        working-directory: ./monorepo
        run: bazel build //...
      # - name: Test bazel monorepo
      #   run: bazel test //...
