name: Pandoc build

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: docker://pandoc/core:3.1.1-ubuntu
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            -t revealjs
            --template pandoc/templates/default.revealjs
            -o docs/devops-slides.html
            pandoc/markdown/devops-slides.md            
      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "test@github.com"
          git config --local user.name "GitHub Action"
          git add ./docs/devops-slides.html
          git commit -m "Add result transformation"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          branch: develop #ignore if your branch is master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true          
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: docs
      #     path: docs            