name: Pandoc build

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: docker://pandoc/core:3.1.1-ubuntu
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            -t revealjs
            --template pandoc/templates/default.revealjs
            -o docs/devops-slides.html
            pandoc/markdown/devops-slides.md            
          
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs            